ProyectoWebTech/config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  resources :comment_comment_reports, defaults: { format: :html }
  resources :comment_comments, defaults: { format: :html }
  resources :event_comments, defaults: { format: :html }
  resources :event_invitations, defaults: { format: :html }
  resources :events
  resources :searches
  resources :organizations
  resources :event_reports
  resources :organization_events
  resources :event_comment_reports
  resources :comment_comment_reports


  resources :conversations do
    resources :msgs
  end

  resources :organization_members

  resources :event_invitations do
    resources :events
  end

  resources :event_comments, shallow: true do
    resources :comment_comments, shallow: true do
      resources :comment_comment_reports, shallow: true
    end
    resources :event_comment_reports, shallow: true
  end

  resources :comment_comments, shallow: true do
    resources :comment_comment_reports, shallow: true
  end
  resources :event_comments, shallow: true do
    resources :comment_comments, shallow: true do
      resources :comment_comment_reports, shallow: true
    end
    resources :event_comment_reports, shallow: true
  end
  resources :events do
    resources :event_dates do
      resources :event_date_votes
    end
    resources :event_comments, shallow: true
    resources :comment_comments
    resources :event_invitations
  end


  resources :organizations do
    resources :organization_members, shallow: true
    resources :organization_files,shallow: true do
      resources :organization_file_reports, shallow:true
    end
    resources :organization_events, shallow: true
    resources :organization_reports, shallow: true
  end

  resources :crud do
    resources :organizations, shallow: true do
      resources :organization_members, shallow: true
      resources :organization_files,shallow: true do
        resources :organization_file_reports, shallow:true
      end
      resources :organization_events, shallow: true
      resources :organization_reports, shallow: true
    end
    resources :events, shallow: true do
      resources :comment_comments, shallow: true do
        resources :comment_comment_reports, shallow: true
      end
      resources :event_comments, shallow: true do
        resources :comment_comments, shallow: true do
          resources :comment_comment_reports, shallow: true
        end
        resources :event_comment_reports, shallow: true
      end
      resources :event_files, shallow: true do
        resources :event_files_reports, shallow: true
      end
      resources :event_dates, shallow:true do
        resources :event_date_votes, shallow: true
      end
      resources :event_invitations, shallow: true
      resources :event_reports, shallow: true
    end
    resources :event_comments, shallow: true do
      resources :comment_comments, shallow: true do
        resources :comment_comment_reports, shallow: true
      end
      resources :event_comment_reports, shallow: true
    end
    resources :comment_comments, shallow: true do
      resources :comment_comment_reports, shallow: true
    end
  end


  resources :admin, defaults: { format: :html }
  resources :comment_comments, defaults: { format: :html }
  resources :comment_comment_reports, defaults: { format: :html }
  resources :date_notifications, defaults: { format: :html }
  resources :events, defaults: { format: :html }
  resources :event_comments, defaults: { format: :html }
  resources :event_comment_reports, defaults: { format: :html }
  resources :event_dates, defaults: { format: :html }
  resources :event_date_votes, defaults: { format: :html }
  resources :event_files, defaults: { format: :html }
  resources :event_file_reports, defaults: { format: :html }
  resources :event_invitations, defaults: { format: :html }
  resources :event_reports, defaults: { format: :html }
  resources :messages, defaults: { format: :html }
  resources :organizations, defaults: { format: :html }
  resources :organization_events, defaults: { format: :html }
  resources :organization_files, defaults: { format: :html }
  resources :organization_file_reports, defaults: { format: :html }
  resources :organization_members, defaults: { format: :html }
  resources :organization_reports, defaults: { format: :html }
  resources :users, defaults: { format: :html }
  resources :user_reports, defaults: { format: :html }

end

ProyectoWebTech/app/models/event.rb
class Event < ApplicationRecord

  has_one_attached :event_banner_photo, dependent: :destroy
  has_many_attached :event_file, dependent: :destroy

  belongs_to :user, optional: true
  has_many :event_invitations , dependent: :destroy
  has_many :event_dates , dependent: :destroy
  has_many :date_notifications , dependent: :destroy
  has_many :event_reports , dependent: :destroy
  has_many :event_comments , dependent: :destroy
  has_many :event_files , dependent: :destroy
  has_many :organization_event , dependent: :destroy

  accepts_nested_attributes_for :event_dates, allow_destroy: true

  validates :title, :description, :ubication, presence: true
end

ProyectoWebTech/app/controllers/api/v1/events_controller.rb
class API::V1::EventsController < APIController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events= Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @events
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json

  def create
    @event = Event.new(event_params)
    @event.user = User.find(params[:user_id])

    if @event.save
      render :show, status: :created, location: @event
    else
      render json: @event.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    if @event.update(event_params)
      render :show, status: :ok, location: api_v1_events_path(@event)
    else
      render json: @event.errors, status: :unprocessable_entity
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.fetch(:event, {}).permit(:title, :ubication, :description, :bannerPhoto, :public, :decition, :min_vote, :start_voting, :finish_voting, :user_id)
    end
end

ProyectoWebTech/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events_invited =  Event.joins(:event_invitations).where(event_invitations:{user_id: current_user})
    @events_own = Event.where(user_id: current_user)

  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event
  end

  # GET /events/new
  def new
    @event = Event.new()
    @event_dates=EventDate.new()
    @event.user = User.first()
    2.times{@event.event_dates.build}
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        a = EventInvitation.create(event: @event, user: @event.user)
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def delete
    @event.delete
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.fetch(:event, {}).permit( :id, :title, :ubication, :description, :public, :decition, :min_vote, :start_voting, :finish_voting, :user_id, :event_dates_id , :event_banner_photo, event_file: [],
                                       event_dates_attributes: [:id, :date, :_destroy], event_date_vote_attributes:[:id, :user_id, :event_date_id, :_destroy])
    end
end

ProyectoWebTech/app/helpers/events_helper.rb
module EventsHelper
end

ProyectoWebTech/app/views/events/_form.html.erb
<div class="row ml-0">
  <%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event_file from being saved:</h2>

        <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.hidden_field :user_id, value: current_user.id %>

    <div class="form-group">
      <%= form.label :title %><br />
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :ubication %><br />
      <%= form.text_area :ubication, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :description %><br />
      <%= form.text_area :description %>
    </div>
    <div class="form-group">
      <%= form.label :decition %><br />
      <%= form.select :decition, [["Your choise",1], ["Date with most votes",2]] %>
    </div>
    <div class="form-group">
      <%= form.label :event_banner_photo %><br />
      <%= form.file_field :event_banner_photo, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :public %><br />
      <%= form.select :public, [["Public",1], ["Private",2]] %>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Add event date</h5>
        <p>You need to add a event date to your newly created event</p>
        <%=form.fields_for :event_dates do |event_dates_form| %>
          <div class="form-group">
            <%= event_dates_form.label :date %><br />
            <%= event_dates_form.datetime_local_field :date, class: "form-control" %>
            <% if action_name == 'edit' %>
              <%= event_dates_form.label "Delete"%>
              <%= event_dates_form.check_box :_destroy %>
            <% end %>
          </div>
        <% end %>

      </div>
    </div>

    <div class="actions">
      <%= form.submit %>

    </div>
  <% end %>
</div>

ProyectoWebTech/app/views/events/_newdate.html.erb
<div class="row ml-0">
  <%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event_file from being saved:</h2>

        <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_for :event_date, :url => {:controller => "event_dates", :action => "create"} do |event_dates_form|%>
      <%= event_dates_form.datetime_local_field :event_id, value: @event.id, type: 'hidden' %>

      <div class="form-group">
        <%= event_dates_form.label :date %><br />
        <%= event_dates_form.datetime_local_field :date, class: "form-control" %>
      </div>

      <div class="actions">
        <%= event_dates_form.submit('New date') %>
      </div>
    <% end %>
  <% end %>
</div>

ProyectoWebTech/app/views/events/_startvoting.html.erb
<div class="row ml-0">
  <%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event_file from being saved:</h2>

        <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <%= form.datetime_local_field :start_voting, value: DateTime.now, type: 'hidden' %>

    <div class="form-group">
      <%= form.label :finish_voting_date %><br />
      <%= form.datetime_local_field :finish_voting, class: "form-control" %>
    </div>

    <%if @event.decition == 1 %>
      <div class="form-group">
        <%= form.label :min_vote %><br />
        <%= form.datetime_local_field :min_vote, class: "form-control" %>
      </div>
    <% end %>

    <div class="actions">
      <%= form.submit('Start votation') %>

    </div>
  <% end %>
</div>

ProyectoWebTech/app/views/events/edit.html.erb
<head>
  <%= stylesheet_link_tag 'global', media:'all', 'data-turbolinks-track': 'reload' %>
</head>

<div class="columna-blanca" >

  <h1>Editing Event</h1>

  <%= render 'form', event: @event %>

  <%= link_to 'Show', @event %>
  <%= link_to 'Back', events_path %>

</div>

ProyectoWebTech/app/views/events/index.html.erb
<head>
  <%= stylesheet_link_tag 'global', media:'all', 'data-turbolinks-track': 'reload' %>
</head>
<div class="columna-azul">
  <div class="columna-blanca">

    <h1 class="center">Events</h1>
    <h2>Your events</h2>
    <% @events_own.each do |event| %>

      <h2 class="columna-blanca"><%=event.title %></h2>

      <% unless event.event_banner_photo.attached? == false %>
        <%= image_tag(url_for(event.event_banner_photo),wide: "400",height: "400") %>
      <% end %>

      <ul class="columna-blanca">
        <li>Ubication: <%= event.ubication %></li>
        <li>User: <%= event.user.name %></li>
        <li><%= link_to 'Show', event %></li>
      </ul>
    <% end %>

    <%= link_to 'New Event', new_event_path %>

  </div>
  <div class="columna-blanca">

    <h2>Event where you are invited</h2>

    <% @events_invited.each do |event| %>
      <h2><%=event.title %></h2>
      <% unless event.event_banner_photo.attached? == false %>
        <%= image_tag(url_for(event.event_banner_photo),wide: "400",height: "400") %>
      <% end %>
      <ul class="columna-blanca">
        <li>Ubication: <%= event.ubication %></li>
        <li>User: <%= event.user.name %></li>
        <li><%= link_to 'Show', event %></li>
      </ul>
    <% end %>

    <br>

  </div>
</div>

ProyectoWebTech/app/views/events/new.html.erb
<head>
  <%= stylesheet_link_tag 'navigation', media:'all', 'data-turbolinks-track': 'reload' %>
</head>

<div class="columna-blanca">

  <h1>New Event</h1>

  <%= render 'form', event: @event %>

  <%= link_to 'Back', events_path %>

</div>

ProyectoWebTech/app/views/events/show.html.erb
<head>
  <%= stylesheet_link_tag 'global', media:'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</head>

<div class = "columna-blanca">
  <div class="columna-blanca" >
    <p id="notice"><%= notice %></p>

    <h1><%=@event.title %></h1>
    <% unless @event.event_banner_photo.attached? == false %>
      <%= image_tag(url_for(@event.event_banner_photo),wide: "400",height: "400") %>
    <% end %>
    <ul class="columna-blanca">
      <il>
        Ubication: <%= @event.ubication %>
      </il>
      <il>
        Owner: <%= @event.user.name %>
      </il>
      <il>
        Description: <%= @event.description %>
      </il>
      <il>
        Created at: <%= @event.created_at %>
      </il>
      <il>
        Issues with this event?:
        <button type="button" class="list-group-item"
                    data-toggle="collapse" data-target="#report"><h4><%= image_tag("Report.jpg",width: '70px') %><br />
          <i class="glyphicon glyphicon-inbox"></i></h4></button>
      </il>

      <li>
        <div id="report" class="collapse" >
          Write your reasons to report:
          <%= form_for :event_report, :url => {:controller => "event_reports", :action => "create"} do |f|%>

            <%= f.number_field :user_id, value: current_user.id, type: "hidden" %>
            <%= f.number_field :event_id, value: @event.id, type: "hidden" %>
            <tr class="form-group">

              <td>
                <%= f.text_field :message, class: "form-control" %>

                <%= f.submit("Submit report") %>
              </td>
            </tr>
          <% end %>
            </div>
      </li>
    </ul>

    <%if current_user.id == @event.user.id or current_user.admin%>
      <div><%= link_to 'Edit', edit_event_path(@event) %></div>
    <% end %>

    <%if @event.start_voting == nil %>
      <div>
        <ul class="columna-blanca">
          <h3>Event Dates</h3>
          <% @event.event_dates.each  do |event_date| %>
            <p><%= event_date.date %></p>
          <% end %>
        </ul>
      </div>
      <%if current_user.admin or current_user.id == @event.user.id %>
        <button type="button" class="list-group-item" style="width:200px;height:50px;"
                data-toggle="collapse" data-target="#new_date"><p>Add new date</p></button>
        <div id="new_date" class="collapse" >
          <br/>
          <%= form_for :event_date, :url => {:controller => "event_dates", :action => "create"} do |event_dates_form|%>
            <%= event_dates_form.datetime_local_field :event_id, value: @event.id, type: 'hidden' %>

            <div class="form-group">
              <%= event_dates_form.label :new_date %><br />
              <%= event_dates_form.datetime_local_field :date, class: "form-control" %>
            </div>

            <div class="actions">
              <%= event_dates_form.submit('New date') %>
            </div>
          <% end %>
        </div>
      <% end %>
      <br/>
      <button type="button" class="list-group-item" style="width:200px;height:50px;"
              data-toggle="collapse" data-target="#Start_voting"><p>Start voting</p></button>
      <div id="Start_voting" class="collapse" >
        <%= render 'startvoting', event: @event %>
      </div>

    <% end %>

    <%if @event.start_voting != nil %>
      <div>
        <h3>Vote for date</h3>
        <div>
          <ul class="columna-blanca">
            <% @event.event_dates.each  do |event_date| %>
              <%= form_for :event_date_vote, :url => {:controller => "event_date_votes", :action => "create"} do |event_date_votes_form|%>

                <%= event_date_votes_form.text_field :user_id, value: current_user.id, type: "hidden" %>
                <%= event_date_votes_form.text_field :event_date_id, value: event_date.id, type: "hidden" %>
                <li class="form-group">
                  <%= event_date_votes_form.submit(event_date.date) %>
                  <%= EventDateVote.where(event_date_id: event_date.id).count() %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
        <%if current_user.admin or current_user.id == @event.user.id %>
          <button type="button" class="list-group-item" style="width:200px;height:50px;"
                  data-toggle="collapse" data-target="#new_date"><p>Add new date</p></button>
          <div id="new_date" class="collapse" >
            <%= form_for :event_date, :url => {:controller => "event_dates", :action => "create"} do |event_dates_form|%>
              <%= event_dates_form.datetime_local_field :event_id, value: @event.id, type: 'hidden' %>

              <div class="form-group">
                <%= event_dates_form.label :new_date %><br />
                <%= event_dates_form.datetime_local_field :date, class: "form-control" %>
              </div>

              <div class="actions">
                <%= event_dates_form.submit('New date') %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>

    <h1>Event Files</h1>
    <div>
      <% @event.event_file.each do |file|%>
        <%= image_tag(url_for(file),wide: "100",height: "100") %>
      <% end %>
    </div>

    <h1>Comments</h1>
    <table class = "columna-blanca">
      <tr>
        <th>
          User
        </th>

        <th class = "columna-blanca">Comment</th>

      </tr>
      <% @event.event_comments.each  do |comment| %>
        <tr>
          <td><%= comment.user.name%></td>

          <td class = "columna-blanca">
            <li ><%= comment.message %></li>
            <li><div id=<%=String(comment.user.name)+String(comment.id)+"c" %> class="collapse">Write your reasons to report:
              <%= form_for :event_comment_report, :url => {:controller => "event_comment_reports", :action => "create"} do |f|%>

                <%= f.number_field :user_id, value: current_user.id, type: "hidden" %>
                <%= f.number_field :event_comment_id, value: comment.id, type: "hidden" %>
          <li class="form-group">

            <li>
              <%= f.text_field :message, class: "form-control" %>

              <%= f.submit("Submit report") %>
            </li>
          </li>
        <% end %></div></li>
            <li>
              <% unless comment.image.attached? == false %>
                <%= image_tag(url_for(comment.image),wide: "100",height: "100") %>
              <% end %>
            </li>
          </td>
          <td><button type="button" class="list-group-item" style="width:90px;height:50px;"
                      data-toggle="collapse" data-target="#<%=String(comment.user.name)+String(comment.id)+"c" %>"><h4><%= image_tag("Report.jpg",width: '60px') %><br />
            <i class="glyphicon glyphicon-inbox"></i></h4></button></td>
          <tr>
            <th></th>
            <th>User</th>
            <th>Reply</th>
          </tr>

          <% comment.comment_comments.each do |commentco| %>

          <tr>

            <td></td>
            <td><%= commentco.user.name%></td>
            <td >
              <div class="columna-blanca"
              <li><%= commentco.message %> </li>
              <li><div id=<%=String(commentco.user.name)+String(commentco.id)+"cc" %> class="collapse"><br>Write your reasons to report:
                <%= form_for :comment_comment_report, :url => {:controller => "comment_comment_reports", :action => "create"} do |f|%>

                  <%= f.number_field :user_id, value: current_user.id, type: "hidden" %>
                  <%= f.number_field :comment_comment_id, value: commentco.id, type: "hidden" %>
                <li class="form-group">

                <li>
                  <%= f.text_field :message, class: "form-control" %>

                  <%= f.submit("Submit report") %>
                </li>
                </li>
          <% end %></div></li>
              <li>
                <% unless commentco.image.attached? == false %>
                  <%= image_tag(url_for(commentco.image),wide: "100",height: "100") %>
                <% end %>
              </li>
              </div>
            </td>
            <td><button type="button" class="list-group-item" style="width:90px;height:50px;"
                        data-toggle="collapse" data-target="#<%=String(commentco.user.name)+String(commentco.id)+"cc" %>"><h4><%= image_tag("Report.jpg",width: '60px') %><br />
              <i class="glyphicon glyphicon-inbox"></i></h4></button></td></td>

          </tr>

          <%end %>
        </div>
          <tr>
            <%= form_for :comment_comment, :url => {:controller => "comment_comments", :action => "create"} do |comment_comment_form|%>

              <%= comment_comment_form.number_field :user_id, value: current_user.id, type: "hidden" %>
              <%= comment_comment_form.number_field :event_comment_id, value: comment.id, type: "hidden" %>


            <tr class="form-group">
              <td></td>
              <td>
                <button type="button" class="list-group-item" style="width:110px;height:50px;"
                        data-toggle="collapse" data-target="#<%=String(comment.user.name)+String(comment.id)+"m" %>"><h7>Reply!<br />
                  <i class="glyphicon glyphicon-inbox"></i></h7></button>
              </td>
              <td>
                <div id=<%=String(comment.user.name)+String(comment.id)+"m" %> class="collapse">
                <%= comment_comment_form.label :message %>
                <%= comment_comment_form.text_field :message, class: "form-control" %>
                <%= comment_comment_form.label :image %>
                <%= comment_comment_form.file_field :image, class: "form-control" %>
                <%= comment_comment_form.submit("Reply") %>
                </div>
              </td>
            </tr>
          <% end %>
          </tr>
      <% end %>
      </tr>
      <%= form_for :event_comment, :url => {:controller => "event_comments", :action => "create"} do |comment_form|%>

        <%= comment_form.text_field :user_id, value: current_user.id, type: "hidden" %>
        <%= comment_form.text_field :event_id, value: @event.id, type: "hidden" %>

        <tr class="form-group">
          <td>
            <button type="button" class="list-group-item" style="width:110px;height:50px;"
                    data-toggle="collapse" data-target="#m" ><h7>Comment!<br />
              <i class="glyphicon glyphicon-inbox"></i></h7></button>
          </td>
          <td>
            <div id="m"  class="collapse">
            <%= comment_form.label :message %>
            <%= comment_form.text_field :message, class: "form-control" %>

            <%= comment_form.label :image %>
            <%= comment_form.file_field :image, class: "form-control" %>
            <%= comment_form.submit("Comment") %>
            </div>
          </td>

          <td></td>
        </tr>
      <% end %>
    </table>
    <hr>
  </div>
  <div class = "columna-blanca">
    <h3>Invitations</h3>
    <ul class="columna-blanca">
      <% @event.event_invitations.each  do |invitation| %>
        <il><%= link_to invitation.user.name, invitation.user %></il>
      <% end %>
    </ul>
    <% $ev = @event.id %>
    <%if current_user.id == @event.user.id or current_user.admin%>
      <div><%= link_to 'Invite more people', new_event_invitation_path() %></div>
    <% end %>
  </div>

      <div>
        <h3>Organizations</h3>
        <ul class="columna-blanca">
          <% Organization.where(id: OrganizationEvent.where(event_id: @event.id)).each  do |organization| %>
            <il><%= link_to organization.name, organization %></il>
          <% end %>
        </ul>
        <% $ev = @event.id %>
        <%if current_user.id == @event.user.id or current_user.admin%>
          <div><%= link_to 'Invite more people', new_organization_event_path() %></div>
        <% end %>
      </div>
  <%= link_to 'Back', events_path %>
</div>