ProyectoWebTech/config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  resources :comment_comment_reports, defaults: { format: :html }
  resources :comment_comments, defaults: { format: :html }
  resources :event_comments, defaults: { format: :html }
  resources :event_invitations, defaults: { format: :html }
  resources :events
  resources :searches
  resources :organizations
  resources :event_reports
  resources :organization_events
  resources :event_comment_reports
  resources :comment_comment_reports


  resources :conversations do
    resources :msgs
  end

  resources :organization_members

  resources :event_invitations do
    resources :events
  end

  resources :event_comments, shallow: true do
    resources :comment_comments, shallow: true do
      resources :comment_comment_reports, shallow: true
    end
    resources :event_comment_reports, shallow: true
  end

  resources :comment_comments, shallow: true do
    resources :comment_comment_reports, shallow: true
  end
  resources :event_comments, shallow: true do
    resources :comment_comments, shallow: true do
      resources :comment_comment_reports, shallow: true
    end
    resources :event_comment_reports, shallow: true
  end
  resources :events do
    resources :event_dates do
      resources :event_date_votes
    end
    resources :event_comments, shallow: true
    resources :comment_comments
    resources :event_invitations
  end


  resources :organizations do
    resources :organization_members, shallow: true
    resources :organization_files,shallow: true do
      resources :organization_file_reports, shallow:true
    end
    resources :organization_events, shallow: true
    resources :organization_reports, shallow: true
  end

  resources :crud do
    resources :organizations, shallow: true do
      resources :organization_members, shallow: true
      resources :organization_files,shallow: true do
        resources :organization_file_reports, shallow:true
      end
      resources :organization_events, shallow: true
      resources :organization_reports, shallow: true
    end
    resources :events, shallow: true do
      resources :comment_comments, shallow: true do
        resources :comment_comment_reports, shallow: true
      end
      resources :event_comments, shallow: true do
        resources :comment_comments, shallow: true do
          resources :comment_comment_reports, shallow: true
        end
        resources :event_comment_reports, shallow: true
      end
      resources :event_files, shallow: true do
        resources :event_files_reports, shallow: true
      end
      resources :event_dates, shallow:true do
        resources :event_date_votes, shallow: true
      end
      resources :event_invitations, shallow: true
      resources :event_reports, shallow: true
    end
    resources :event_comments, shallow: true do
      resources :comment_comments, shallow: true do
        resources :comment_comment_reports, shallow: true
      end
      resources :event_comment_reports, shallow: true
    end
    resources :comment_comments, shallow: true do
      resources :comment_comment_reports, shallow: true
    end
  end


  resources :admin, defaults: { format: :html }
  resources :comment_comments, defaults: { format: :html }
  resources :comment_comment_reports, defaults: { format: :html }
  resources :date_notifications, defaults: { format: :html }
  resources :events, defaults: { format: :html }
  resources :event_comments, defaults: { format: :html }
  resources :event_comment_reports, defaults: { format: :html }
  resources :event_dates, defaults: { format: :html }
  resources :event_date_votes, defaults: { format: :html }
  resources :event_files, defaults: { format: :html }
  resources :event_file_reports, defaults: { format: :html }
  resources :event_invitations, defaults: { format: :html }
  resources :event_reports, defaults: { format: :html }
  resources :messages, defaults: { format: :html }
  resources :organizations, defaults: { format: :html }
  resources :organization_events, defaults: { format: :html }
  resources :organization_files, defaults: { format: :html }
  resources :organization_file_reports, defaults: { format: :html }
  resources :organization_members, defaults: { format: :html }
  resources :organization_reports, defaults: { format: :html }
  resources :users, defaults: { format: :html }
  resources :user_reports, defaults: { format: :html }

end

ProyectoWebTech/app/models/comment_comment_report.rb
class CommentCommentReport < ApplicationRecord
  belongs_to :comment_comment, optional: true
  belongs_to :user, optional: true
end

ProyectoWebTech/app/controllers/comment_comment_reports_controller.rb
class CommentCommentReportsController < ApplicationController
  before_action :set_comment_comment_report, only: [:show, :edit, :update, :destroy]

  # GET /comment_comment_reports
  # GET /comment_comment_reports.json
  def index
    @comment_comment_reports = CommentCommentReport.all
  end

  # GET /comment_comment_reports/1
  # GET /comment_comment_reports/1.json
  def show
  end

  # GET /comment_comment_reports/new
  def new
    @comment_comment_report = CommentCommentReport.new
  end

  # GET /comment_comment_reports/1/edit
  def edit
  end

  # POST /comment_comment_reports
  # POST /comment_comment_reports.json
  def create
    @comment_comment_report = CommentCommentReport.new(comment_comment_report_params)

    respond_to do |format|
      if @comment_comment_report.save
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render :show, status: :created, location: @comment_comment_report }
      else
        format.html { render :new }
        format.json { render json: @comment_comment_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comment_comment_reports/1
  # PATCH/PUT /comment_comment_reports/1.json
  def update
    respond_to do |format|
      if @comment_comment_report.update(comment_comment_report_params)
        format.html { redirect_to @comment_comment_report, notice: 'Comment comment report was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment_comment_report }
      else
        format.html { render :edit }
        format.json { render json: @comment_comment_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comment_comment_reports/1
  # DELETE /comment_comment_reports/1.json
  def destroy
    @comment_comment_report.destroy
    respond_to do |format|
      format.html { redirect_to comment_comment_reports_url, notice: 'Comment comment report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment_comment_report
      @comment_comment_report = CommentCommentReport.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_comment_report_params
      params.fetch(:comment_comment_report, {}).permit(:id, :comment_comment_id, :user_id, :message)
    end
end

ProyectoWebTech/app/helpers/comment_comment_reports_helper.rb
module CommentCommentReportsHelper
end

ProyectoWebTech/app/views/comment_comment_reports/_form.html.erb
<%= form_with(model: comment_comment_report, local: true) do |form| %>
  <% if comment_comment_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment_comment_report.errors.count, "error") %> prohibited this comment_comment_report from being saved:</h2>

      <ul>
        <% comment_comment_report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ProyectoWebTech/app/views/comment_comment_reports/edit.html.erb
<h1>Editing Comment Comment Report</h1>

<%= render 'form', comment_comment_report: @comment_comment_report %>

<%= link_to 'Show', @comment_comment_report %> |
<%= link_to 'Back', comment_comment_reports_path %>

ProyectoWebTech/app/views/comment_comment_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comment Comment Reports</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comment_comment_reports.each do |comment_comment_report| %>
      <tr>
        <td><%= link_to 'Show', comment_comment_report %></td>
        <td><%= link_to 'Edit', edit_comment_comment_report_path(comment_comment_report) %></td>
        <td><%= link_to 'Destroy', comment_comment_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment Comment Report', new_comment_comment_report_path %>

ProyectoWebTech/app/views/comment_comment_reports/new.html.erb
<h1>New Comment Comment Report</h1>

<%= render 'form', comment_comment_report: @comment_comment_report %>

<%= link_to 'Back', comment_comment_reports_path %>

ProyectoWebTech/app/views/comment_comment_reports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_comment_report_path(@comment_comment_report) %> |
<%= link_to 'Back', comment_comment_reports_path %>