ProyectoWebTech/config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  resources :comment_comment_reports, defaults: { format: :html }
  resources :comment_comments, defaults: { format: :html }
  resources :event_comments, defaults: { format: :html }
  resources :event_invitations, defaults: { format: :html }
  resources :events
  resources :searches
  resources :organizations
  resources :event_reports
  resources :organization_events
  resources :event_comment_reports
  resources :comment_comment_reports


  resources :conversations do
    resources :msgs
  end

  resources :organization_members

  resources :event_invitations do
    resources :events
  end

  resources :event_comments, shallow: true do
    resources :comment_comments, shallow: true do
      resources :comment_comment_reports, shallow: true
    end
    resources :event_comment_reports, shallow: true
  end

  resources :comment_comments, shallow: true do
    resources :comment_comment_reports, shallow: true
  end
  resources :event_comments, shallow: true do
    resources :comment_comments, shallow: true do
      resources :comment_comment_reports, shallow: true
    end
    resources :event_comment_reports, shallow: true
  end
  resources :events do
    resources :event_dates do
      resources :event_date_votes
    end
    resources :event_comments, shallow: true
    resources :comment_comments
    resources :event_invitations
  end


  resources :organizations do
    resources :organization_members, shallow: true
    resources :organization_files,shallow: true do
      resources :organization_file_reports, shallow:true
    end
    resources :organization_events, shallow: true
    resources :organization_reports, shallow: true
  end

  resources :crud do
    resources :organizations, shallow: true do
      resources :organization_members, shallow: true
      resources :organization_files,shallow: true do
        resources :organization_file_reports, shallow:true
      end
      resources :organization_events, shallow: true
      resources :organization_reports, shallow: true
    end
    resources :events, shallow: true do
      resources :comment_comments, shallow: true do
        resources :comment_comment_reports, shallow: true
      end
      resources :event_comments, shallow: true do
        resources :comment_comments, shallow: true do
          resources :comment_comment_reports, shallow: true
        end
        resources :event_comment_reports, shallow: true
      end
      resources :event_files, shallow: true do
        resources :event_files_reports, shallow: true
      end
      resources :event_dates, shallow:true do
        resources :event_date_votes, shallow: true
      end
      resources :event_invitations, shallow: true
      resources :event_reports, shallow: true
    end
    resources :event_comments, shallow: true do
      resources :comment_comments, shallow: true do
        resources :comment_comment_reports, shallow: true
      end
      resources :event_comment_reports, shallow: true
    end
    resources :comment_comments, shallow: true do
      resources :comment_comment_reports, shallow: true
    end
  end


  resources :admin, defaults: { format: :html }
  resources :comment_comments, defaults: { format: :html }
  resources :comment_comment_reports, defaults: { format: :html }
  resources :date_notifications, defaults: { format: :html }
  resources :events, defaults: { format: :html }
  resources :event_comments, defaults: { format: :html }
  resources :event_comment_reports, defaults: { format: :html }
  resources :event_dates, defaults: { format: :html }
  resources :event_date_votes, defaults: { format: :html }
  resources :event_files, defaults: { format: :html }
  resources :event_file_reports, defaults: { format: :html }
  resources :event_invitations, defaults: { format: :html }
  resources :event_reports, defaults: { format: :html }
  resources :messages, defaults: { format: :html }
  resources :organizations, defaults: { format: :html }
  resources :organization_events, defaults: { format: :html }
  resources :organization_files, defaults: { format: :html }
  resources :organization_file_reports, defaults: { format: :html }
  resources :organization_members, defaults: { format: :html }
  resources :organization_reports, defaults: { format: :html }
  resources :users, defaults: { format: :html }
  resources :user_reports, defaults: { format: :html }

end

ProyectoWebTech/app/models/organization.rb
class Organization < ApplicationRecord
  has_one_attached :organization_banner_photo, dependent: :destroy

  has_one_attached :organization_banner_photo, dependent: :delete_all

  belongs_to :user, optional: true

  has_many :organization_members , dependent: :destroy
  has_many :organization_files, dependent: :destroy
  has_many :organization_reports, dependent: :destroy
  has_many :organization_events, dependent: :destroy

end

ProyectoWebTech/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations_invited =  Organization.joins(:organization_members).where(organization_members:{user_id: current_user})
    @organizations_own = Organization.where(user_id: current_user)
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @public_events = OrganizationEvent.where(organization_id: @organization.id)

  end

  # GET /organizations/new
  def new
    @organization = Organization.new
    @organization.user = User.first
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)
    respond_to do |format|
      if @organization.save
        a = OrganizationMember.create(user: @organization.user, organization: @organization)
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params())
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params

      params.fetch(:organization, {}).permit( :id, :name, :description, :user_id,
                                              organization_member_attributes: [:id, :user_id, :_destroy])  #:organization_banner_photo

    end
end

ProyectoWebTech/app/helpers/organizations_helper.rb
module OrganizationsHelper
end

ProyectoWebTech/app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>

  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
        <% organization.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.admin or action_name == 'edit' %>
    <div class="form-group">
      <%= form.label :User %>
      <%= form.collection_select :user_id, User.all, :id, :name, include_blank: true %>
    </div>
  <% elsif action_name == 'new'%>
    <%= form.hidden_field :user_id, value: current_user.id %>
  <% end %>

  <div class="form-group">
    <%= form.label :name %> <br/>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %><br/>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :organization_banner_photo %><br/>
    <%= form.file_field :organization_banner_photo, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ProyectoWebTech/app/views/organizations/edit.html.erb
<head>
  <%= stylesheet_link_tag 'navigation', media:'all', 'data-turbolinks-track': 'reload' %>
</head>

<div class="columna-blanca">

  <h1>Editing Organization</h1>

  <%= render 'form', organization: @organization %>

  <%= link_to 'Show', @organization %>
  <%= link_to 'Back', organizations_path %>

</div>

ProyectoWebTech/app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<head>
  <%= stylesheet_link_tag 'navigation', media:'all', 'data-turbolinks-track': 'reload' %>
</head>

<div class="columna-azul">
  <div class="columna-blanca">

    <h1>Organizations</h1>
    <h4>Your organizations</h4>
    <% @organizations_own.each do |org| %>
      <h3><%= org.name %></h3>
      <% unless org.organization_banner_photo.attached? == false %>
        <%= image_tag(url_for(org.organization_banner_photo),wide: "400",height: "400") %>
      <% end %>
      <ul class="columna-blanca">
        <li><%= org.name %></li>
        <li><%= org.description %></li>
        <li><%= org.created_at %></li>
        <li><%= link_to 'Show', org %></li>
      </ul>
    <% end %>
    <%= link_to 'New Organization', new_organization_path %>
  </div>

    <hr>

  <div class="columna-blanca">
    <h4>Organizations where you participate</h4>
    <% @organizations_invited.each do |org| %>
      <h3><%= org.name %></h3>
      <% unless org.organization_banner_photo.attached? == false %>
        <%= image_tag(url_for(org.organization_banner_photo),wide: "400",height: "400") %>
      <% end %>
      <ul class="columna-blanca">
        <li><%= org.name %></li>
        <li><%= org.description %></li>
        <li><%= org.created_at %></li>
        <li><%= link_to 'Show', org %></li>
      </ul>
    <% end %>

  </div>

</div>

ProyectoWebTech/app/views/organizations/new.html.erb
<head>
  <%= stylesheet_link_tag 'navigation', media:'all', 'data-turbolinks-track': 'reload' %>
</head>

<div class="columna-blanca">

  <h1>New Organization</h1>
  <%= form_with(model: @organization, local: true) do |form| %>
  <%= form.text_field :user_id, value: User.first.id, type: "hidden" %>
  <%= render 'form', organization: @organization %>
  <% end %>
  <%= link_to 'Back', organizations_path %>

</div>

ProyectoWebTech/app/views/organizations/show.html.erb
<head>
  <%= stylesheet_link_tag 'global', media:'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</head>


<div class="columna-blanca">
  <p id="notice"><%= notice %></p>

  <h1><%=@organization.name %></h1>
  <% unless @organization.organization_banner_photo.attached? == false %>
    <%= image_tag(url_for(@organization.organization_banner_photo),wide: "400",height: "400") %>
  <% end %>

  <ul class="columna-blanca">
    <li>Owner: <%= @organization.user.name %></li>
    <li>Description: <%= @organization.description %></li>
    <%if current_user.id == @organization.user.id or current_user.admin%>
      <li><%= link_to 'Edit', edit_organization_path(@organization) %><button type="button" class="list-group-item" style="width:110px;height:50px;" data-toggle="collapse" data-target="#report"><h4><%= image_tag("Report.jpg",width: '70px') %></h4></button></li>
      <div id="report" class="collapse" >
        Write your reasons to report:
        <%= form_for :organization_report, :url => {:controller => "organization_reports", :action => "create"} do |f|%>

          <%= f.number_field :user_id, value: current_user.id, type: "hidden" %>
          <%= f.number_field :organization_id, value: @organization.id, type: "hidden" %>
          <tr class="form-group">

            <td>
              <%= f.text_field :message, class: "form-control" %>

              <%= f.submit("Submit report") %>
            </td>
          </tr>
        <% end %>
      </div>
    <% end %>
  </ul>

  <div class = "columna-blanca">
    <h3>Organization members</h3>
    <ul class="columna-blanca">
      <% @organization.organization_members.each  do |member| %>
        <il><%= member.user.name  %></il>
      <% end %>
    </ul>
    <% $org = @organization.id %>
    <%if current_user.id == @organization.user.id or current_user.admin%>
      <div><%= link_to 'Invite more people', new_organization_member_path() %></div>
    <% end %>
  </div>

  <h1>Organization Events</h1>
  <% @public_events.each do |org_event| %>
    <h2 class="columna-blanca"><%=Event.find(org_event.event_id).title %></h2>

    <% unless Event.find(org_event.event_id).event_banner_photo.attached? == false %>
      <%= image_tag(url_for(Event.find(org_event.event_id).event_banner_photo),wide: "400",height: "400") %>
    <% end %>

    <ul class="columna-blanca">
      <li>Ubication: <%= Event.find(org_event.event_id).ubication %></li>
      <li>User: <%= Event.find(org_event.event_id).user.name %></li>
      <li><%= link_to 'Show', Event.find(org_event.event_id) %></li>
    </ul>
  <% end %>


  <%= link_to 'Back', organizations_path %>
</div>