ProyectoWebTech/config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  resources :comment_comment_reports, defaults: { format: :html }
  resources :comment_comments, defaults: { format: :html }
  resources :event_comments, defaults: { format: :html }
  resources :event_invitations, defaults: { format: :html }
  resources :events
  resources :searches
  resources :organizations
  resources :event_reports
  resources :organization_events
  resources :event_comment_reports
  resources :comment_comment_reports


  resources :conversations do
    resources :msgs
  end

  resources :organization_members

  resources :event_invitations do
    resources :events
  end

  resources :event_comments, shallow: true do
    resources :comment_comments, shallow: true do
      resources :comment_comment_reports, shallow: true
    end
    resources :event_comment_reports, shallow: true
  end

  resources :comment_comments, shallow: true do
    resources :comment_comment_reports, shallow: true
  end
  resources :event_comments, shallow: true do
    resources :comment_comments, shallow: true do
      resources :comment_comment_reports, shallow: true
    end
    resources :event_comment_reports, shallow: true
  end
  resources :events do
    resources :event_dates do
      resources :event_date_votes
    end
    resources :event_comments, shallow: true
    resources :comment_comments
    resources :event_invitations
  end


  resources :organizations do
    resources :organization_members, shallow: true
    resources :organization_files,shallow: true do
      resources :organization_file_reports, shallow:true
    end
    resources :organization_events, shallow: true
    resources :organization_reports, shallow: true
  end

  resources :crud do
    resources :organizations, shallow: true do
      resources :organization_members, shallow: true
      resources :organization_files,shallow: true do
        resources :organization_file_reports, shallow:true
      end
      resources :organization_events, shallow: true
      resources :organization_reports, shallow: true
    end
    resources :events, shallow: true do
      resources :comment_comments, shallow: true do
        resources :comment_comment_reports, shallow: true
      end
      resources :event_comments, shallow: true do
        resources :comment_comments, shallow: true do
          resources :comment_comment_reports, shallow: true
        end
        resources :event_comment_reports, shallow: true
      end
      resources :event_files, shallow: true do
        resources :event_files_reports, shallow: true
      end
      resources :event_dates, shallow:true do
        resources :event_date_votes, shallow: true
      end
      resources :event_invitations, shallow: true
      resources :event_reports, shallow: true
    end
    resources :event_comments, shallow: true do
      resources :comment_comments, shallow: true do
        resources :comment_comment_reports, shallow: true
      end
      resources :event_comment_reports, shallow: true
    end
    resources :comment_comments, shallow: true do
      resources :comment_comment_reports, shallow: true
    end
  end


  resources :admin, defaults: { format: :html }
  resources :comment_comments, defaults: { format: :html }
  resources :comment_comment_reports, defaults: { format: :html }
  resources :date_notifications, defaults: { format: :html }
  resources :events, defaults: { format: :html }
  resources :event_comments, defaults: { format: :html }
  resources :event_comment_reports, defaults: { format: :html }
  resources :event_dates, defaults: { format: :html }
  resources :event_date_votes, defaults: { format: :html }
  resources :event_files, defaults: { format: :html }
  resources :event_file_reports, defaults: { format: :html }
  resources :event_invitations, defaults: { format: :html }
  resources :event_reports, defaults: { format: :html }
  resources :messages, defaults: { format: :html }
  resources :organizations, defaults: { format: :html }
  resources :organization_events, defaults: { format: :html }
  resources :organization_files, defaults: { format: :html }
  resources :organization_file_reports, defaults: { format: :html }
  resources :organization_members, defaults: { format: :html }
  resources :organization_reports, defaults: { format: :html }
  resources :users, defaults: { format: :html }
  resources :user_reports, defaults: { format: :html }

end

ProyectoWebTech/app/controllers/crud_controller.rb
class CrudController < ApplicationController

  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events =  Event.all
    @comments =  Event.all
    @organizations =  Organization.all
    @users = User.all


  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event
  end

  # GET /events/new
  def new
    @event = Event.new()
    @event_dates=EventDate.new()
    @event.user = User.first()
    2.times{@event.event_dates.build}
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.fetch(:event, {}).permit( :id, :title, :ubication, :description, :public, :decition, :min_vote, :start_voting, :finish_voting, :bannerphoto, :user_id, :event_dates_id ,
                                     event_dates_attributes: [:id, :date, :_destroy])
  end
end

ProyectoWebTech/app/helpers/crud_helper.rb
module CrudHelper
end

ProyectoWebTech/app/views/crud/_form.html.erb
<div class="row ml-0">
  <%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event_file from being saved:</h2>

        <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.hidden_field :user_id, value: User.first.id %>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :ubication %>
      <%= form.text_area :ubication, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
    <div class="form-group">
      <%= form.label :decition %>
      <%= form.select :decition, [["hola e.e",1], ["chao e.e",2]] %>
    </div>
    <div class="form-group">
      <%= form.label :bannerPhoto %>
      <%= form.text_field :bannerPhoto, class: "form-control" %>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Add event date</h5>
        <p>You need to add a event date to your newly created event</p>
        <%=form.fields_for :event_dates do |event_dates_form| %>
          <div class="form-group">
            <%= event_dates_form.label :date %>
            <%= event_dates_form.datetime_local_field :date, class: "form-control" %>
            <% if action_name == 'edit' %>
              <%= event_dates_form.label "Delete"%>
              <%= event_dates_form.check_box :_destroy %>
            <% end %>
          </div>
        <% end %>

      </div>
    </div>


    <div class="actions">
      <%= form.submit %>

    </div>
  <% end %>
</div>

ProyectoWebTech/app/views/crud/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

ProyectoWebTech/app/views/crud/index.html.erb
<p id="notice"><%= notice %></p>

<head>
  <%= stylesheet_link_tag 'global', media:'all', 'data-turbolinks-track': 'reload' %>
</head>
<div class="columna-azul">

<div class="columna-blanca">

  <h1 class="center">Every Comment</h1>
  <% @events.each do |event| %>
    <table>
      <h2><%=event.title %></h2>
        <% event.event_comments.each  do |comment| %>
          <tr>
            <td><%= comment.user.name%></td>
            <td><%= comment.message %></td>
            <td><%= button_to 'Edit', edit_event_comment_path(comment), method: :get %></td>
            <td><%= button_to 'Destroy', event_comment_path(comment) , method: :delete%></td>
            <% comment.comment_comments.each do |commentco| %>
            <tr>
              <td><%= commentco.user.name%></td>
              <td><%= commentco.message %></td>
              <td><%= button_to 'Edit', edit_comment_comment_path(commentco), method: :get  %></td>
              <td><%= button_to 'Destroy', comment_comment_path(commentco) , method: :delete%></td>
            </tr>
          <%end %>
          </tr>

        <%end %>
    </table>
  <% end %>
  <h3 class="center">New Comment</h3>
  <%= button_to 'New Created Comment', href="http://localhost:3000/event_comments/new", method: :get  %>
  <%= button_to 'New Created Comment on other Comment', href="http://localhost:3000/comment_comments/new", method: :get %>
</div>
<div class="columna-blanca">
  <h1 class="center">Every Organization</h1>
  <% @organizations.each do |orga| %>
    <tr>
      <td><%= orga.user.name%></td>
      <td><%= orga.name %></td>
      <td><%= button_to 'Edit', edit_organization_path(orga) , method: :get %></td>
      <td><%= button_to 'Destroy', organization_path(orga) , method: :delete%></td>

    </tr>
  <% end %>
  <br>
  <tr></tr>
  <h3 class="center">New Organization</h3>
  <%= button_to 'New Organization', href="http://localhost:3000/organizations/new", method: :get %>
<br>

</div>
  <div class="columna-blanca">

    <h1 class="center">All the Events</h1>
    <% @events.each do |event| %>

      <h2 class="columna-blanca"><%=event.title %></h2>
      <ul class="columna-blanca">
        <li>Ubication: <%= event.ubication %></li>
        <li>User: <%= event.user.name %></li>
        <li>Mail: <%= event.user.email %></li>
        <li><%= button_to 'Show', event, method: :get  %></li>
        <li><%= button_to 'Edit', edit_event_path(event), method: :get %></li>
        <li><%= button_to 'Destroy', event_path(event), method: :delete%></li>
      </ul>
    <% end %>
    <h3 class="center">New Event</h3>
    <%= button_to 'New Event', new_event_path , method: :get%>

  </div>
  <div class="columna-blanca">

    <h1 class="center">All the Users</h1>
    <% @users.each do |us| %>

      <h2 class="columna-blanca"><%=us.name %></h2>
      <ul class="columna-blanca">
        <li>User: <%= us.name %></li>
        <li>Mail: <%= us.email %></li>
        <li><%= button_to 'Show', user_path(us) , method: :get%></li>
        <li><%= button_to 'Edit', edit_user_path(us) , method: :get %></li>
        <li><%= button_to 'Destroy', user_path(us) , method: :delete%></li>
      </ul>
    <% end %>
    <h3 class="center">New User</h3>
    <%= button_to 'New User',  href="/users/sign_up", method: :get %>

  </div>
</div>

ProyectoWebTech/app/views/crud/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

ProyectoWebTech/app/views/crud/show.html.erb
<p id="notice"><%= notice %></p>

<head>
  <%= stylesheet_link_tag 'global', media:'all', 'data-turbolinks-track': 'reload' %>
</head>

<div class="columna-blanca" >

  <h1><%=@events.title %></h1>

  <table>
    <tbody>
    <tr>
      <th>
        Ubication
      </th>
      <th>
        Owner
      </th>
      <th>
        Description
      </th>
    </tr>
      <tr>
        <td><%= @events.ubication %></td>
        <td><%= @events.user.name %></td>
        <td><%= @events.description %></td>
      </tr>
    </tbody>
  </table>

  <h1>Comments</h1>
  <table>
    <tr>
      <th>
        User
      </th>
      <th>
        Comment
      </th>
    </tr>
    <h2><%=@event.title %></h2>
    <% @event.event_comments.each  do |comment| %>
      <tr>
        <td><%= comment.user.name%></td>
        <td><%= comment.message %></td>

        <% comment.comment_comments.each do |commentco| %>
        <tr>
          <td><%= commentco.user.name%></td>
          <td><%= commentco.message %></td>
        </tr>
      <%end %>
      </tr>

    <%end %>
  </table>
  <hr>
  <%= link_to 'Edit', edit_event_path(@event) %>
  <%= link_to 'Back', events_path %>
</div>